#! /bin/bash

cd /home/ec2-user/statsd

CONTAINER_NAME="grafana-dashboard"
if [ $(docker ps -a | grep $CONTAINER_NAME | awk '{print $NF}' | wc -l) -gt 0 ];then
	docker stop $CONTAINER_NAME
	docker rm $CONTAINER_NAME
fi

docker run \
  --detach \
   --publish=80:80 \
   --publish=81:81 \
   --publish=8125:8125/udp \
   --publish=8126:8126 \
   --name $CONTAINER_NAME \
   --volume=$(pwd)/data/whisper:/opt/graphite/storage/whisper \
   --volume=$(pwd)/data/elasticsearch:/var/lib/elasticsearch \
   --volume=$(pwd)/data/grafana:/opt/grafana/data \
   --volume=$(pwd)/log/graphite:/opt/graphite/storage/log \
   --volume=$(pwd)/log/elasticsearch:/var/log/elasticsearch \
   --volume=$(pwd)/configs/grafana/home.json:/opt/grafana/public/dashboards/home.json \
   --volume=$(pwd)/configs/graphite/storage-schemas.conf:/opt/graphite/conf/storage-schemas.conf \
   --volume=$(pwd)/configs/statsd/config.js:/src/statsd/config.js \
   -e GF_USERS_ALLOW_SIGN_UP=false \
   -e GF_USERS_ALLOW_ORG_CREATE=false \
   kamon/grafana_graphite
